// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/events": {
            "get": {
                "description": "公開イベントを指定ソート順で返す。認証不要。\nsort は \"created_at\"(デフォルト) / \"event_date\" のみ許可。不正値はデフォルトに戻す。\norder は \"desc\"(デフォルト) / \"asc\" のみ許可。不正値はデフォルトに戻す。\nprifileはProfileSummaryを返す。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "イベント一覧取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ソートカラム(created_at|event_date, default: created_at)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ソート順(asc|desc, default: desc)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "取得件数(default 20, 最大 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "取得開始位置(default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証済みユーザーが新規イベントを投稿する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "イベント投稿",
                "parameters": [
                    {
                        "description": "イベント投稿リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateEventRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/events/{id}": {
            "get": {
                "description": "指定されたイベントIDの詳細情報を取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "イベント詳細取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "イベントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証済みユーザー自身のプロフィールを返す(初回アクセス時に自動作成)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "本人プロフィール取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/uploads/presign": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定した kind/contentType に対応する R2 tmp 領域への PUT 署名付き URL を返す。\n返却された uploadUrl に直接 PUT することでクライアントがファイルをアップロードできる。\n取得した objectKey をイベント作成時の imageObjectKeys/pdfObjectKeys に渡すこと。\nkind=\"image\": image/jpeg, image/png のみ対応（WebP は MVP 非対応）。\nkind=\"pdf\": application/pdf のみ対応。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "upload"
                ],
                "summary": "アップロード用署名付き URL 発行",
                "parameters": [
                    {
                        "description": "presign リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.PresignRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.PresignResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "サーバーが正常に稼働しているか確認する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "ヘルスチェック",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateEventRequest": {
            "description": "イベント投稿に必要な情報。",
            "type": "object",
            "required": [
                "costs",
                "description",
                "eventDate",
                "location",
                "title"
            ],
            "properties": {
                "capacity": {
                    "description": "Capacity は定員（任意・0=未設定・正数=定員）。",
                    "type": "integer",
                    "minimum": 0,
                    "example": 30
                },
                "costs": {
                    "description": "Costs は費用内訳（1件以上必須）。",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventCostInput"
                    }
                },
                "description": {
                    "description": "Description はイベント説明（必須）。",
                    "type": "string",
                    "example": "春の桜を観察するイベントです。"
                },
                "eventDate": {
                    "description": "EventDate はイベント開催日時(RFC3339)（必須）。",
                    "type": "string",
                    "example": "2026-07-01T10:00:00Z"
                },
                "externalUrl": {
                    "description": "ExternalURL は関連URLs（任意・255文字以内・http/https）。",
                    "type": "string",
                    "maxLength": 255,
                    "example": "https://example.com/event"
                },
                "imageObjectKeys": {
                    "description": "ImageObjectKeys は画像オブジェクトキーの一覧（任意）。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "items": {
                    "description": "Items は持ち物リスト（任意）。",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventItemInput"
                    }
                },
                "location": {
                    "description": "Location は開催場所（必須・255文字以内）。",
                    "type": "string",
                    "maxLength": 255,
                    "example": "東京都新宿御苑"
                },
                "pdfObjectKeys": {
                    "description": "PdfObjectKeys はPDFオブジェクトキーの一覧（任意・各要素255文字以内）。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "description": "Title はイベントタイトル（必須・255文字以内）。",
                    "type": "string",
                    "maxLength": 255,
                    "example": "サクラ観察会"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateEventResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "CreatedAt はレコード作成日時(RFC3339)。",
                    "type": "string",
                    "example": "2026-06-23T12:00:00Z"
                },
                "id": {
                    "description": "ID は生成されたイベントの UUID。",
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は機械可読なエラーコード。",
                    "type": "string",
                    "example": "internal_error"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。",
                    "type": "string",
                    "example": "サーバー内部でエラーが発生しました"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ErrorBody"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventCostInput": {
            "type": "object",
            "required": [
                "category"
            ],
            "properties": {
                "category": {
                    "description": "Category は費用カテゴリ（例: \"参加費\"）。",
                    "type": "string",
                    "maxLength": 255
                },
                "cost": {
                    "description": "Cost は費用（円）。0 以上の整数。",
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventCostResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "cost": {
                    "type": "integer"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventItemInput": {
            "type": "object",
            "required": [
                "item"
            ],
            "properties": {
                "isRequired": {
                    "description": "IsRequired は必須かどうか。",
                    "type": "boolean"
                },
                "item": {
                    "description": "Item は持ち物名（例: \"双眼鏡\"）。",
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventItemResponse": {
            "type": "object",
            "properties": {
                "isRequired": {
                    "type": "boolean"
                },
                "item": {
                    "type": "string"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventListResponse": {
            "type": "object",
            "properties": {
                "events": {
                    "description": "Events はイベントサマリーの一覧。",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventSummary"
                    }
                },
                "limit": {
                    "description": "Limit は正規化後の実際に使われた取得件数。",
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "description": "Offset は正規化後の実際に使われた取得開始位置。",
                    "type": "integer",
                    "example": 0
                },
                "totalCount": {
                    "description": "TotalCount はフィルタなし全件数。クライアントが最終ページ offset を算出するために使う。",
                    "type": "integer",
                    "example": 153
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventResponse": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "costs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventCostResponse"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "eventDate": {
                    "type": "string"
                },
                "externalUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imageObjectKeys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventItemResponse"
                    }
                },
                "location": {
                    "type": "string"
                },
                "pdfObjectKeys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "profile": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ProfileSummary"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventSummary": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "CreatedAt はレコード作成日時(RFC3339)。",
                    "type": "string",
                    "example": "2026-06-22T12:00:00Z"
                },
                "eventDate": {
                    "description": "EventDate はイベント開催日時(RFC3339)。",
                    "type": "string",
                    "example": "2026-07-01T10:00:00Z"
                },
                "id": {
                    "description": "ID はイベントの一意識別子(UUID)。",
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                },
                "location": {
                    "description": "Location は開催場所（文字列）。",
                    "type": "string",
                    "example": "東京都新宿御苑"
                },
                "profile": {
                    "description": "ProfileSummary は投稿者プロフィールのサマリー情報。",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ProfileSummary"
                        }
                    ]
                },
                "profileId": {
                    "description": "ProfileID は投稿者のプロフィール ID(UUID)。",
                    "type": "string",
                    "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
                },
                "title": {
                    "description": "Title はイベントタイトル。",
                    "type": "string",
                    "example": "サクラ観察会"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status はサーバの稼働状態。正常時は \"ok\"。",
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は機械可読なエラーコード。",
                    "type": "string",
                    "example": "internal_error"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。",
                    "type": "string",
                    "example": "サーバー内部でエラーが発生しました"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorBody"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.PresignRequest": {
            "description": "アップロード用署名付き URL の発行リクエスト。",
            "type": "object",
            "required": [
                "contentType",
                "kind"
            ],
            "properties": {
                "contentType": {
                    "description": "ContentType は MIME タイプ。\n画像: \"image/jpeg\" / \"image/png\"\nPDF: \"application/pdf\"",
                    "type": "string",
                    "example": "image/jpeg"
                },
                "kind": {
                    "description": "Kind はアップロードするファイルの種別。\"image\" または \"pdf\" のみ有効。",
                    "type": "string",
                    "enum": [
                        "image",
                        "pdf"
                    ],
                    "example": "image"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.PresignResponse": {
            "description": "アップロード用署名付き URL とオブジェクトキー。",
            "type": "object",
            "properties": {
                "expiresAt": {
                    "description": "ExpiresAt は署名付き URL の有効期限(RFC3339)。",
                    "type": "string",
                    "example": "2026-07-01T10:05:00Z"
                },
                "objectKey": {
                    "description": "ObjectKey はアップロード先のオブジェクトキー。イベント作成時に imageObjectKeys/pdfObjectKeys に渡す。",
                    "type": "string",
                    "example": "natueve/tmp/profile-uuid/uuid.jpg"
                },
                "uploadUrl": {
                    "description": "UploadURL はファイルを直接 PUT するための署名付き URL。",
                    "type": "string",
                    "example": "https://xxxxx.r2.cloudflarestorage.com/natuportal/natueve/tmp/profile-uuid/uuid.jpg?X-Amz-..."
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ProfileResponse": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "description": "AvatarURL はアバター画像 URL(未設定なら空)。",
                    "type": "string",
                    "example": "https://example.com/avatar.png"
                },
                "createdAt": {
                    "description": "CreatedAt はプロフィール作成日時(RFC3339)。",
                    "type": "string",
                    "example": "2026-06-22T12:00:00Z"
                },
                "displayName": {
                    "description": "DisplayName は表示名(未設定なら空)。",
                    "type": "string",
                    "example": "なちゅいべ太郎"
                },
                "email": {
                    "description": "Email はユーザーのメールアドレス。",
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "description": "ID は Supabase Auth のユーザー ID(UUID)。",
                    "type": "string",
                    "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
                },
                "updatedAt": {
                    "description": "UpdatedAt はプロフィール更新日時(RFC3339)。",
                    "type": "string",
                    "example": "2026-06-22T12:00:00Z"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ProfileSummary": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "description": "AvatarURL はアバター画像 URL(未設定なら空)。",
                    "type": "string",
                    "example": "https://example.com/avatar.png"
                },
                "displayName": {
                    "description": "DisplayName は表示名(未設定なら空)。",
                    "type": "string",
                    "example": "なちゅいべ太郎"
                },
                "id": {
                    "description": "ID は Supabase Auth のユーザー ID(UUID)。",
                    "type": "string",
                    "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は機械可読なエラーコード。",
                    "type": "string",
                    "example": "unauthorized"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。",
                    "type": "string",
                    "example": "認証が必要です"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorBody"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は機械可読なエラーコード。",
                    "type": "string",
                    "example": "invalid_request"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。",
                    "type": "string",
                    "example": "タイトルは必須です"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorBody"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Supabase Auth が発行した JWT を \"Bearer \u003ctoken\u003e\" 形式で指定する",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "NatuEve API",
	Description:      "NatuEve のバックエンド API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
