basePath: /
definitions:
  github_com_GokujyouKaisennDonnburi_NatuIve_API_internal_model.HealthResponse:
    properties:
      status:
        description: Status はサーバの稼働状態。正常時は "ok"。
        example: ok
        type: string
    type: object
info:
  contact: {}
  description: NatuIve のバックエンド API
  title: NatuIve API
  version: "1.0"
paths:
  /health:
    get:
      description: サーバーが正常に稼働しているか確認する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_GokujyouKaisennDonnburi_NatuIve_API_internal_model.HealthResponse'
      summary: ヘルスチェック
      tags:
      - system
swagger: "2.0"
